USE [DSNP3]
GO

SELECT [dbo].[Contrat].[IdContrat]
      ,[dbo].[Contrat].[IdIndividu]
      ,[dbo].[Contrat].[DateDebut]
      ,[dbo].[Contrat].[CodeStatutConv]
      ,[dbo].[Contrat].[CodeStatutCatRetraiteCompl]
      ,[dbo].[Contrat].[CodePcsEse]
      ,[dbo].[Contrat].[CodeCompltPcsEse]
      ,[dbo].[Contrat].[LibelleEmploi]
      ,[dbo].[Contrat].[CodeNature]
      ,[dbo].[Contrat].[CodeDispPolitiquePublique]
      ,[dbo].[Contrat].[Numero]
      ,[dbo].[Contrat].[DateFinPrev]
      ,[dbo].[Contrat].[CodeUniteQuotite]
      ,[dbo].[Contrat].[QuotiteTravailCategorie]
      ,[dbo].[Contrat].[QuotiteTravailContrat]
      ,[dbo].[Contrat].[ModaliteExerciceTempsTravail]
      ,[dbo].[Contrat].[ComplementBaseRegimeObligatoire]
      ,[dbo].[Contrat].[CodeCCN]
      ,[dbo].[Contrat].[CodeRegimeMaladie]
      ,[dbo].[Contrat].[LieuTravail]
      ,[dbo].[Contrat].[CodeRegimeRisqueVieillesse]
      ,[dbo].[Contrat].[CodeMotifRecours]
      ,[dbo].[Contrat].[CodeCaisseCP]
      ,[dbo].[Contrat].[TravailleurAEtrangerSS]
      ,[dbo].[Contrat].[CodeMotifExclusion]
      ,[dbo].[Contrat].[CodeStatutEmploi]
      ,[dbo].[Contrat].[CodeDelegataireRisqueMaladie]
      ,[dbo].[Contrat].[CodeEmploiMultiple]
      ,[dbo].[Contrat].[CodeEmployeurMultiple]
      ,[dbo].[Contrat].[CodeMetier]
      ,[dbo].[Contrat].[CodeRegimeRisqueAT]
      ,[dbo].[Contrat].[CodeRisqueAccidentTravail]
      ,[dbo].[Contrat].[PositionConventionCollective]
      ,[dbo].[Contrat].[CodeStatutCatAPECITA]
      ,[dbo].[Contrat].[SalarieTpsPartielCotisTpsPlein]
      ,[dbo].[Contrat].[RemunerationPourboire]
      ,[dbo].[Contrat].[SIRETEtabUtilisateur]
      ,[dbo].[Contrat].[FPCodeComplPcsEse]
      ,[dbo].[Contrat].[FPNaturePoste]
      ,[dbo].[Contrat].[FPQuotiteTravailTempsComplet]
      ,[dbo].[Contrat].[TauxTravailTempsPartiel]
      ,[dbo].[Contrat].[CodeCatService]
      ,[dbo].[Contrat].[FPIndiceBrut]
      ,[dbo].[Contrat].[FPIndiceMajore]
      ,[dbo].[Contrat].[FPNBI]
      ,[dbo].[Contrat].[FPIndiceBrutOrigine]
      ,[dbo].[Contrat].[FPIndiceBrutCotiEmploiS]
      ,[dbo].[Contrat].[FPAncEmployPublic]
      ,[dbo].[Contrat].[FPMaintienTraitContractuelT]
      ,[dbo].[Contrat].[FPTypeDetachement]
      ,[dbo].[Contrat].[TauxServiceActif]
      ,[dbo].[Contrat].[NiveauRemuneration]
      ,[dbo].[Contrat].[Echelon]
      ,[dbo].[Contrat].[CoefficientHierarchique]
      ,[dbo].[Contrat].[StatutBOETH]
      ,[dbo].[Contrat].[CompltDispositifPublic]
      ,[dbo].[Contrat].[MiseDispoExterneIndividu]
      ,[dbo].[Contrat].[CatClassementfinale]
      ,[dbo].[Contrat].[CollegeCNIEG]
      ,[dbo].[Contrat].[AmenagTpsTravActivParti]
      ,[dbo].[Contrat].[DateChargement]
      ,[dbo].[Contrat].[IdDateChargement]
      ,[dbo].[Contrat].[TauxDeductForfFraisPro]
      ,[dbo].[Contrat].[NumeroInterneEPublic]
      ,[dbo].[Contrat].[TypeGestionAC]
      ,[dbo].[Contrat].[DateAdhesion]
      ,[dbo].[Contrat].[CodeAffAssChomage]
      ,[dbo].[Contrat].[StatutOrgSpectacle]
      ,[dbo].[Contrat].[GenreNavigation]
      ,[dbo].[Contrat].[Grade]
      ,[dbo].[Contrat].[FPIndiceCTI]
      ,[dbo].[Contrat].[FINESSGeographique]
      ,[dbo].[Declaration].[IdDeclaration]
      ,[dbo].[Declaration].[DateDeclaration]
  FROM [dbo].[Contrat]
  INNER JOIN [dbo].[Individu]
	ON [dbo].[Contrat].IdIndividu = [dbo].[Individu].IdIndividu
  INNER JOIN [dbo].[Etablissement]
	ON [dbo].[Individu].IdEtablissement = [dbo].[Etablissement].IdEtablissement
  INNER JOIN [dbo].[Declaration]
	ON [dbo].[Etablissement].IdDeclaration = [dbo].[Declaration].IdDeclaration
  WHERE [dbo].[Declaration].[IdDateChargement] >= AAAAMMJJ1
  AND [dbo].[Declaration].[IdDateChargement] < AAAAMMJJ2

GO
