USE [DSNP3]
GO

SELECT [dbo].[ContratChangement].[IdContratChangement]
      ,[dbo].[ContratChangement].[IdContrat]
      ,[dbo].[ContratChangement].[DateModification]
      ,[dbo].[ContratChangement].[CodeStatutConv]
      ,[dbo].[ContratChangement].[CodeStatutCatRetraiteCompl]
      ,[dbo].[ContratChangement].[CodeNature]
      ,[dbo].[ContratChangement].[CodeDispPolitiquePublique]
      ,[dbo].[ContratChangement].[CodeUniteQuotite]
      ,[dbo].[ContratChangement].[QuotiteTravailContrat]
      ,[dbo].[ContratChangement].[ModaliteExercieTempsTravail]
      ,[dbo].[ContratChangement].[ComplementBaseRegimeObligatoire]
      ,[dbo].[ContratChangement].[CodeCCN]
      ,[dbo].[ContratChangement].[SiretEtab]
      ,[dbo].[ContratChangement].[LieuTravail]
      ,[dbo].[ContratChangement].[Numero]
      ,[dbo].[ContratChangement].[CodeMotifRecours]
      ,[dbo].[ContratChangement].[TravailleurAEtrangerSS]
      ,[dbo].[ContratChangement].[CodePcsEse]
      ,[dbo].[ContratChangement].[CodeCompltPcsEse]
      ,[dbo].[ContratChangement].[DateDebut]
      ,[dbo].[ContratChangement].[QuotiteTravailCategorie]
      ,[dbo].[ContratChangement].[CodeCaisseCP]
      ,[dbo].[ContratChangement].[CodeRisque]
      ,[dbo].[ContratChangement].[CodeStatutCatAPECITA]
      ,[dbo].[ContratChangement].[SalarieTpsPartielCotisTpsPlein]
      ,[dbo].[ContratChangement].[ProfondeurRecalculPaie]
      ,[dbo].[ContratChangement].[FPCodeComplPcsEse]
      ,[dbo].[ContratChangement].[FPNaturePoste]
      ,[dbo].[ContratChangement].[FPQuotiteTravailTempsComplet]
      ,[dbo].[ContratChangement].[TauxTravailTempsPartiel]
      ,[dbo].[ContratChangement].[CodeCatService]
      ,[dbo].[ContratChangement].[FPIndiceBrut]
      ,[dbo].[ContratChangement].[FPIndiceMajore]
      ,[dbo].[ContratChangement].[FPNBI]
      ,[dbo].[ContratChangement].[FPIndiceBrutOrigine]
      ,[dbo].[ContratChangement].[FPIndiceBrutCotiEmploiS]
      ,[dbo].[ContratChangement].[FPAncEmployPublic]
      ,[dbo].[ContratChangement].[FPMaintienTraitContractuelT]
      ,[dbo].[ContratChangement].[TauxServiceActif]
      ,[dbo].[ContratChangement].[NiveauRemuneration]
      ,[dbo].[ContratChangement].[Echelon]
      ,[dbo].[ContratChangement].[CoefficientHierarchique]
      ,[dbo].[ContratChangement].[StatutBOETH]
      ,[dbo].[ContratChangement].[CompltDispositifPublic]
      ,[dbo].[ContratChangement].[MiseDispoExterneIndividu]
      ,[dbo].[ContratChangement].[CatClassementfinale]
      ,[dbo].[ContratChangement].[CollegeCNIEG]
      ,[dbo].[ContratChangement].[AmenagTpsTravActivParti]
      ,[dbo].[ContratChangement].[FPTypeDetachement]
      ,[dbo].[ContratChangement].[DateChargement]
      ,[dbo].[ContratChangement].[IdDateChargement]
      ,[dbo].[ContratChangement].[TauxDeductForfFraisPro]
      ,[dbo].[ContratChangement].[CodeRegimeMaladie]
      ,[dbo].[ContratChangement].[CodeRegimeRisqueVieillesse]
      ,[dbo].[ContratChangement].[PositionConventionCollective]
      ,[dbo].[ContratChangement].[CodeRisqueAccidentTravail]
      ,[dbo].[ContratChangement].[CodeStatutEmploi]
      ,[dbo].[ContratChangement].[CodeEmploiMultiple]
      ,[dbo].[ContratChangement].[CodeEmployeurMultiple]
      ,[dbo].[ContratChangement].[Grade]
      ,[dbo].[ContratChangement].[FPIndiceCTI]
      ,[dbo].[ContratChangement].[FINESSGeographique]
      ,[dbo].[Declaration].[IdDeclaration]
      ,[dbo].[Declaration].[DateDeclaration]
  FROM [dbo].[ContratChangement]
  INNER JOIN [dbo].[Contrat]
	ON [dbo].[ContratChangement].IdContrat = [dbo].[Contrat].IdContrat
  INNER JOIN [dbo].[Individu]
	ON [dbo].[Contrat].IdIndividu = [dbo].[Individu].IdIndividu
  INNER JOIN [dbo].[Etablissement]
	ON [dbo].[Individu].IdEtablissement = [dbo].[Etablissement].IdEtablissement
  INNER JOIN [dbo].[Declaration]
	ON [dbo].[Etablissement].IdDeclaration = [dbo].[Declaration].IdDeclaration
  WHERE [dbo].[Declaration].[IdDateChargement] >= AAAAMMJJ1
  AND [dbo].[Declaration].[IdDateChargement] < AAAAMMJJ2

GO
