USE [DSNP3]
GO

SELECT [dbo].[Etablissement].[IdEtablissement]
      ,[dbo].[Declaration].[IdDeclaration]
      ,[dbo].[Etablissement].[Siren]
      ,[dbo].[Etablissement].[NICEntre]
      ,[dbo].[Etablissement].[CodeAPEN]
      ,[dbo].[Etablissement].[VoieEntre]
      ,[dbo].[Etablissement].[CPEntre]
      ,[dbo].[Etablissement].[LocaliteEntre]
      ,[dbo].[Etablissement].[CompltDistributionEntre]
      ,[dbo].[Etablissement].[CompltVoieEntre]
      ,[dbo].[Etablissement].[EffectifMoyenEntrepriseFinPeriode]
      ,[dbo].[Etablissement].[CodePaysEntr]
      ,[dbo].[Etablissement].[ImplantationEntreprise]
      ,[dbo].[Etablissement].[DateDebPerRef]
      ,[dbo].[Etablissement].[DateFinPerRef]
      ,[dbo].[Etablissement].[RaisonSocialeEntr]
      ,[dbo].[Etablissement].[NIC]
      ,[dbo].[Etablissement].[CodeAPET]
      ,[dbo].[Etablissement].[VoieEtab]
      ,[dbo].[Etablissement].[CP]
      ,[dbo].[Etablissement].[Localite]
      ,[dbo].[Etablissement].[CompltDistributionEtab]
      ,[dbo].[Etablissement].[CompltVoieEtab]
      ,[dbo].[Etablissement].[EffectifFinPeriode]
      ,[dbo].[Etablissement].[Codepays]
      ,[dbo].[Etablissement].[NatureJuridiqueEmployeur]
      ,[dbo].[Etablissement].[DateClotureExerciceComptable]
      ,[dbo].[Etablissement].[DateAdhesionTESECEA]
      ,[dbo].[Etablissement].[DateSortieTESECEA]
      ,[dbo].[Etablissement].[CodeINSEECommune]
      ,[dbo].[Etablissement].[DateEcheanceApplique]
      ,[dbo].[Etablissement].[CategorieJuridique]
      ,[dbo].[Etablissement].[EnseigneEtablissement]
      ,[dbo].[Etablissement].[DateChargement]
      ,[dbo].[Etablissement].[IdDateChargement]
      ,[dbo].[Etablissement].[CodeConvCollectiveApplic]
      ,[dbo].[Etablissement].[CodeConvCollectivePrinci]
      ,[dbo].[Etablissement].[OprateurCompetences]
      ,[dbo].[Declaration].[DateDeclaration]
  FROM [dbo].[Etablissement]
  INNER JOIN [dbo].[Declaration]
	ON [dbo].[Etablissement].IdDeclaration = [dbo].[Declaration].IdDeclaration
  WHERE [dbo].[Declaration].[IdDateChargement] >= AAAAMMJJ1
  AND [dbo].[Declaration].[IdDateChargement] < AAAAMMJJ2
GO
