USE [DSNP3]
GO

SELECT [dbo].[Individu].[IdIndividu]
      ,[dbo].[Individu].[IdEtablissement]
      ,[dbo].[Individu].[NIRDeclare]
      ,[dbo].[Individu].[NomFamille]
      ,[dbo].[Individu].[NomUsage]
      ,[dbo].[Individu].[Prenoms]
      ,[dbo].[Individu].[CodeSexe]
      ,[dbo].[Individu].[DateNaissance]
      ,[dbo].[Individu].[LieuNaissance]
      ,[dbo].[Individu].[Voie]
      ,[dbo].[Individu].[CP]
      ,[dbo].[Individu].[Localite]
      ,[dbo].[Individu].[CodePays]
      ,[dbo].[Individu].[Distribution]
      ,[dbo].[Individu].[CodeUE]
      ,[dbo].[Individu].[CodeDepartNaissance]
      ,[dbo].[Individu].[CodePaysNaissance]
      ,[dbo].[Individu].[CompltLocalisation]
      ,[dbo].[Individu].[CompltVoie]
      ,[dbo].[Individu].[Mel]
      ,[dbo].[Individu].[Matricule]
      ,[dbo].[Individu].[NTT]
      ,[dbo].[Individu].[NombreEnfantcharge]
      ,[dbo].[Individu].[StatutEtrangerFiscal]
      ,[dbo].[Individu].[Embauche]
      ,[dbo].[Individu].[NiveauFormation]
      ,[dbo].[Individu].[NIR]
      ,[dbo].[Individu].[DateSNGI]
      ,[dbo].[Individu].[NomFamilleSNGI]
      ,[dbo].[Individu].[PrenomsSNGI]
      ,[dbo].[Individu].[NomMaritalSNGI]
      ,[dbo].[Individu].[CodeResultSNGI]
      ,[dbo].[Individu].[IndicCertifSNGI]
      ,[dbo].[Individu].[ComNaissSNGI]
      ,[dbo].[Individu].[CodeDeptNaissSNGI]
      ,[dbo].[Individu].[PaysNaissSNGI]
      ,[dbo].[Individu].[DateNIRSNGI]
      ,[dbo].[Individu].[DateDecesSNGI]
      ,[dbo].[Individu].[DateChargement]
      ,[dbo].[Individu].[IdDateChargement]
      ,[dbo].[Individu].[EstCodifie]
      ,[dbo].[Individu].[NiveauDiplome]
      ,[dbo].[Declaration].[IdDeclaration]
      ,[dbo].[Declaration].[DateDeclaration]
  FROM [dbo].[Individu]
  INNER JOIN [dbo].[Etablissement]
	ON [dbo].[Individu].IdEtablissement = [dbo].[Etablissement].IdEtablissement
  INNER JOIN [dbo].[Declaration]
	ON [dbo].[Etablissement].IdDeclaration = [dbo].[Declaration].IdDeclaration
  WHERE [dbo].[Declaration].[IdDateChargement] >= AAAAMMJJ1
  AND [dbo].[Declaration].[IdDateChargement] < AAAAMMJJ2
GO
